version: '3.0'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  db:
    driver: local
